name: Package Extension
on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.0, v2.1.3, etc.
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create extension package
        run: |
          # Extension directory
          EXTENSION_DIR="."
          # Package name based on the tag
          PACKAGE_NAME="my-extension-${{ steps.tag.outputs.tag }}.zip"
          # Create ZIP with exclusions
          zip -r -FS "$PACKAGE_NAME" . \
            --exclude "*.git*" \
            --exclude "*.github*" \
            --exclude "*.vscode/*" \
            --exclude "*.log" \
            --exclude "*.tmp" \
            --exclude "*.temp" \
            --exclude "*.code-workspace" \
            --exclude "LICENSE"
           
          echo "Created package: $PACKAGE_NAME"
          ls -la "$PACKAGE_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HideMieterPlus-${{ steps.tag.outputs.tag }}
          path: "*.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: HideMieterPlus (${{ steps.tag.outputs.tag }})
          files: HideMieterPlus-${{ steps.tag.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
